/*
 * toon shader
 * author: gnya
 */

#include "group_id.h"
#include "shadow.h"

#define MAX_LOOP 50


/*
 * This function wraps `trace(pos, dir, ...)` for tracing.
 */
int trace_ray(point pos, vector dir, int finite, float len) {
    if (finite) {
        return trace(pos, dir, "maxdist", max(0.0, len));
    } else {
        return trace(pos, dir);
    }
}


/*
 * This function checks whether lights from the direction of
 * a given light source reaches the point of current interest.
 */
int shadow(vector L, float ray_length, float cutoff, float eps) {
    int this_group = 0;
    int this_props = 0;  // Unused.
    int this_backfacing = dot(Ng, L) < 0.0;

    get_this_shadow_group(this_group, this_props);

    int count = 0;

    point pos = P + ray_offset(L, cutoff);
    int finite = ray_length >= 0.0;
    float len = ray_length;
    point last_pos = pos;

    if (this_backfacing) {
        pos -= L * eps;
    } else {
        pos += L * eps;
    }

    int hit_group = 0;
    int hit_props = 0;

    for (; count < MAX_LOOP && trace_ray(pos, L, finite, len); count++) {
        get_hit_shadow_group(hit_group, hit_props);

        if (this_group == 0 || this_group != hit_group) {
            if (hit_props == 0) {
                return 1;
            } else if (hit_props == 1 && !this_backfacing) {
                return 1;
            }
        }

        getmessage("trace", "P", pos);
        len -= distance(pos, last_pos);
        last_pos = pos;
        pos += L * eps;
    }

    if (count == MAX_LOOP) {
        warning("the max loop has been reached.");
    }

    return 0;
}

shader material(
    vector Light = vector(0.0, 0.0, 0.0)
    [[ string widget = "null" ]],
    float RayLength = 0.0
    [[ string widget = "null" ]],
    vector Normal = N
    [[ string widget = "null" ]],
    float Cutoff = 0.1,
    float Reflectance = 0.5,
    float Exponent = 10.0,

    /*
     * This is a hack necessary to determine whether the currently
     * used renderer can use OSL and perform fallback processing.
     */
    output int IsCycles = 1
    [[ string widget = "boolean" ]],

    output float Diffuse = 0.0,
    output float Specular = 0.0
) {
    Diffuse = clamp(dot(Light, Normal), 0.0, 1.0);

    if (Reflectance != 0.0) {
        vector R = reflect(normalize(Light), Normal);
        
        Specular = pow(max(0.0, dot(-I, R)), Exponent) * Reflectance;
    }

    if (Diffuse != 0.0) {
        vector L = normalize(Light);

        if (shadow(L, RayLength, Cutoff, 1.0e-5)) {
            Diffuse = 0.0;
            Specular = 0.0;
        }
    }
}
